configserver: true
bus: true

accountNumberPattern: 99999
accountNumber.serviceId: SPARROW-REVIEWS
telephoneNumberPattern: 12345
telephoneNumber.serviceId: SPARROW-RECOMMENDATIONS

genreMlId: 1
genreMlId.serviceId: SPARROW-CATALOG
genreMlId: 2
genreMlId.serviceId: SPARROW-WEB


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.sparrow-service-registry.credentials.uri:http://127.0.0.1:8762}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
